### ISSUE TITLE
Make the app work with other schools

### ISSUE THREAD

**Issue by forcemagic** [forcemagic/kreta-remastered#2]
Currently, the application has one upstream target: [`https://klik031937001.e-kreta.hu`](https://klik031937001.e-kreta.hu).

There are many other links like this (assuming that the format is `klikXXXXXXXXX.e-kreta.hu`, where "X" is a numerical digit). A multi-url support should be added with modifying the `AccountStoreHelper`.

**Comment by wnb235** [comment]
It should be an EMERG at this point
