### ISSUE TITLE
Visual Changes for beta v1.1

### ISSUE THREAD

**Issue by wnb235** [forcemagic/kreta-remastered#29]
Ann  1. Make the margins bigger in Announcements page.

G  2 Figure out how to make the margins between the grades smaller.

Av  3. Can you put the whole diagram closer to the right side of the page, without changing the position of the values of the y axis? (Shrink the distance from the right side to its 3 quarters)

Ann  4. If you tap on an announcement, open it in roll down view. (And delete the line under them)

G  5. Do something with the half year and end year grade, to make it look less unbearably ugly.

G  6. Make the line under the name of the subject blueish when opened.

Sc  7. The calendar opens way too slowly, can you seed it up?

Sc  8. Can you change the font of the M: Sept. 19. ... stuff back to what it was before, and put a Tab where it needs to be?

Ann 9. Make the dot at the top left corner of the announcements indicate if you have opened it before.

G = Grades page
Av = Average page
Sc = Schedule
Ann = Announcements page

**Comment by wnb235** [comment]
That "blueish" should be the color of the weekdaySelector.

**Comment by forcemagic** [comment]
Some comments:

1. Sure, will do.
2. There is no possible way :disappointed: Unfortunately. We have to change the master design.
3. Good idea :+1:  
4. Line already deleted, dialog is on its way
5. Okay, I'll use the reference pictures that you sent me:

   ![21868128_517083598627767_583145350_o](https://user-images.githubusercontent.com/25160976/30655261-41230624-9de5-11e7-9c76-ce37972f7852.png)

6. Will do, probably no. :one: on my priority list
7. I'll look into it. Maybe I can cache the calendar's settings... Somehow. Or I might find a new library for it.
8. I'll try.
9. Kinda linked to no. :four:, but sure, I'll do it :smiley: 

I'll be done by tomorrow. I hope.

**Comment by forcemagic** [comment]
Great news! I found a way to make no. 2 happen!! I'm on it.
