### ISSUE TITLE
UI Changes vol II.

### ISSUE THREAD

**Issue by forcemagic** [forcemagic/kreta-remastered#31]
1. Set the minimum value to 1 on the diagram.

2. Delete the OK button from the calendar, so when you tap on a date it opens immediately, and replace the arrow that indicates the current date with the blue dot that now indicates the chosen date.

   No need for that current date indicator, as the current day would be selected as the default one.

3. Fix am pm stuff.

   AM/PM labels should be there at the schedule items.

4. When you add a profile it should log in as well.

5. Add loading bar to the loading screen.

6. Fab to replace the currentWeekDay row.

7. Bring the current date to the right top corner in floating.

8. I'll sent you the overall desing of 1.2, asap.

9. Limit the password length at 16 digit.

**Comment by wnb235** [comment]
*button

**Comment by wnb235** [comment]
Let's revise those points:
Point 6 and 7 are pretty unnecessary in 1.2.
If you set the minimum value of the diagram to 1, only the integer values should be displayed along the y-axis.
If you open a roll down menu the other ones should close.
Beside the other 6 points, listed in the issue above, there is nothing else to do.
I'll send you the new design for 1.2 tomorrow or the day after that, release in the weekend.

**Comment by wnb235** [comment]
10. The whole fingerprint encryption should appear only on phones with a fingerprint scanner. If someone doesn't have a fp saved in one's phone when the app is first launched, but later the guy adds one, the app should notice it, and ask the user about fp encryption.

11. Change the blacks to various shades of white, more specifically on the highest quality design preview you've ever seen.
![fjimg_20170926_221007](https://user-images.githubusercontent.com/32106512/30882847-9e4eb31e-a30a-11e7-9b7b-0f32265e3875.jpg)

12. Change the color of the add profile button to that blue.

**Comment by wnb235** [comment]
Also I had the unfortunate pleasure of using the Hungarian version, which is, no offense, just horrible. Please get some help from Roberta or something.

**Comment by forcemagic** [comment]
I know xDD that doesn't LGTM either. I don't wanna bother Ms. Roberta, so I'll try to improve my vocabulary by myself 😄

**Comment by wnb235** [comment]
I think animations would look great. If you have the time, please add a couple. I miss them, especially in the roll down menus.

**Comment by forcemagic** [comment]
Sure. Remember Lottie? These little icons/animations can improve user experience a lot :D See this: https://www.lottiefiles.com Also, I'll add some neat animations, don't worry :smiley:

**Comment by wnb235** [comment]
First thing first, don't forget about the issues above, to be exact number 3, 4, 5 and 9.

Other changes:
1. As you open the app and unlock it, it should automatically log into the last profile.

2. Add white margin to the button of the calendar view.

3. For some reason the calendar always opens the actual month instead of the one you're currently at.

4. I'll figure out a new placement for the buttons and stuff on the schedule.

5. Have you noticed that we keep delaying the release date? More importantly, the comment with picture of the 'design preview' has a point 1, if it's possible (I know it's not) do it. Just do it.

**Comment by wnb235** [comment]
The last items on the schedule and average (and presumably on announcements too) pages still have a line at the button. That's UNACCEPTABLE!!!!

**Comment by wnb235** [comment]
![](https://i.imgur.com/zsc1fv3.png)

**Comment by wnb235** [comment]
Oh, and can you change the name of announcements to bulletin please?

**Comment by forcemagic** [comment]
Yes. Yes, I can. :smile:

**Comment by wnb235** [comment]
https://youtu.be/07So_lJQyqw

**Comment by wnb235** [comment]
Guess that's all....
Or is it?

**Comment by forcemagic** [comment]
I hope so.

**Comment by wnb235** [comment]
No no no no no, we sadly forgot about the half year grade😑

**Comment by wnb235** [comment]
Luckily its appearance isn't that different form the others'. Just change the background colour.

**Comment by wnb235** [comment]
I just realized that we needn't stick to the kind of reversed order of the grades in sort by subject. The only reason for not having the latest grade on top was the design in 1.0, but now whit the new one it seems point less. Reversing the current order would result in an increase of structural clarity.

**Comment by wnb235** [comment]
**Progress bar.** 
Now it's on the list. Happy now?

**Comment by wnb235** [comment]
Don't forget to change the icon and the feature graphics🙃

**Comment by forcemagic** [comment]
@WhyNotBro235 That's for another issue :smile: First, we have to fix what's on this list, then we can migrate to ZsirKreta.
