### ISSUE TITLE
I have bold ideas

### ISSUE THREAD

**Issue by wnb235** [forcemagic/kreta-remastered#39]
Here are some unacceptably complicated features:

In advanced settings encryption can be turned off =>
Other apps can access your grades (nobody cares about security) =>
Google Assistant can tell you about your schedule and grades!

#suchusefulfeature #nobodycaresaboutsecurity
#letAIaccessallyourdata
#AIsupremacy

**Comment by forcemagic** [comment]
Thank you for the suggestion. Will reconsider it in 2019.
