### ISSUE TITLE
UI changes vol. III

### ISSUE THREAD

**Issue by wnb235** [forcemagic/kreta-remastered#41]
1. I sent you the design preview for the Schedule via Messenger

2. Make the Bulletins follow the overall design language.

3. When you tap the new profile button it opens a new page or something, I'd recommend doing the same with the delete profile stuff.

4. When you add a profile and it finishes downloading the data, it opens the previous profile instead of the new one.

5. On the Add profile page change the appearance of the button, not a big deal but I'll send you the design preview.

6. Change the pic in the drawer to those crayons, I'll send you the pic via email.

7. Coming soon... (this will be about the design of the school picker menu)

**Comment by wnb235** [comment]
Somehow the delay of the roll down menu has disappeared from the Averages page.

The calendar icon in the top left corner of the Schedule should map to the current date, also it should be grey.
Change the colour of the week day dot to that blue please.

Don’t know if you noticed, but in Hungarian the abbreviation for Thursday is a C, so I guess it’s called Cütörtök now.

When you tap on the Delete profiles button even though one of the profiles does say “you can’t delete this...”, you totally can. After you deleted all the existing profiles and went back, you can see the last profile. When you close the app, it notices that there are no profiles to be found there and next time it starts with the Add profile page.

(The other points, that are not mentioned here, are still waiting for the next version)

**Comment by wnb235** [comment]
Can you change the order of the subjects on Sort by subject page? Now it's the same order as it is on the webpage, I think we should make it a bit more logical.

**Comment by wnb235** [comment]
Calendar view animation starts lagging when the selected date is not the current date.

Add some delay to the roll down animation in Averages.

**Comment by forcemagic** [comment]
@WhyNotBro235 Alphabetical or what kind of ordering at the sort by subjects? I can't really do anything with the CompactCalendarView, but I think I can help the animation manually. I'll look into it.

**Comment by wnb235** [comment]
I thought we abandoned the idea of alphabetical order, because we didn't want Art to be on the top of the list. In spite of that, it might be a better idea than letting Kréta mess with it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by forcemagic** [comment]
@WhyNotBro235 Maybe reversed alphabetical? And I'm thinking about sorting averages too. But about that... I think the best average on top should be nice.

**Comment by wnb235** [comment]
Couldn't the best average be on the top in both pages?

**Comment by forcemagic** [comment]
@WhyNotBro235 Yeah, sure and let's create a 0.5s overhead load time, like we haven't had problems with that nasty stuff. My short answer is NO. :smile: 

## Explanation

The DataStore has two separate objects: Grades and Averages. Grades are requested at the grades fragment to fuel both of the layouts. Averages are the same, but they're only requested at the averages fragment. If I combine the two, we'd get +0.5s approximate load time, because of the DataStore - SQLite connection. We'd also allocate unnecessarily large memory.

**Comment by wnb235** [comment]
Well, do whatever you want, I just want some kind of order

**Comment by forcemagic** [comment]
@WhyNotBro235 I might be able to devise a solution, but for now, let's worry about the actual looks, not the ordering. Just to remind: this issue is called `UI Changes`

**Comment by wnb235** [comment]
Add a back button to the top left corner of Add profile page, same as on Manage profiles page.

**Comment by wnb235** [comment]
Map the calendar icon to the current date, and make it gray pls.

In the drawer wouldn't it make more sense to put the friendly name to the top, and the student ID to the button row? Also the name could be a bit bigger.

In Bulletins the line button should start where the text begins (it's like a 30 dp padding on the left).

The animation on Sort by subject has the same problem as the Averages. If you open a roll down stuff above an opened one, as it closes in front of the element beneath. Maybe a different animation rather than corrections in the existing one could solve this more easily.

Aaaaaand I guess that's all, the only thing left to design is the school picker, so basically I'm done :smile:
