### ISSUE TITLE
Almost there! (UI changes vol. IV)

### ISSUE THREAD

**Issue by wnb235** [forcemagic/kreta-remastered#46]
Soooo...

1. The date format in Bulletin is different from the others

2. Frankly, that thing you did with the Averages is just kind of ugly. If it looked like the sort by subject, that would be nice. (so basically just switch the colours)

3. The spacing between the items in Averages is a too big, something in between the previous and the current one would be better.

Can't wait to criticise the school picker and the notification. :smile:

**Comment by forcemagic** [comment]
I guess... these things have already been implemented.
