### ISSUE TITLE
Last touches for Alakazam

### ISSUE THREAD

**Issue by wnb235** [forcemagic/kreta-remastered#47]
1. "Choose school" title above school picker

2. Error message instead of crash when no school is chosen 

3. Substitution beneath te separator, as long as the separato

4. Average color #fff, graph background colour #fbfbfb thus you can put a shadow beneath the #fff coloured stuff 

?? 5. Slide animation when tapped on the gray calendar icon ??

**Comment by wnb235** [comment]
Add profile button should be inactive while you are offline

Back arrow to add profile page

**Comment by wnb235** [comment]
Exchange it 2 calendar icons

**Comment by wnb235** [comment]
The one in the drawer should be in the top right corner and vise versa

**Comment by WhyNotBro235** [comment]
Abort point 2, averaging the averages can't be bone in such simple way, I described it

**Comment by wnb235** [comment]
If you get 2 (or I guess more) of the same grade with the same date, the app counts them as just one

**Comment by wnb235** [comment]
The graph should only show the last change in the average on the days you get grades
